Repository volcano-sh/charts, pull requests merged in 2019-07, with the labels that each got.

#6 Update charts
  .gitignore
  chart/volcano/templates/admission-config.yaml
  chart/volcano/templates/admission.yaml
Labels: approved, lgtm, size/S

#5 Updating the Job CRD
  chart/volcano/templates/batch_v1alpha1_job.yaml
Labels: approved, lgtm, size/XS

#7 Enable CI for chart project
  .travis.yml
  Makefile
  chart/volcano/templates/admission.yaml
  hack/e2e-kind-config.yaml
  hack/run-e2e-kind.sh
Labels: approved, lgtm, size/L

#8 Update vk- to vc-
  Makefile
  chart/volcano/README.md
  chart/volcano/templates/batch_v1alpha1_job.yaml
  chart/volcano/values.yaml
Labels: approved, lgtm, size/S

#9 Renaming the field name from eventlist to events
  chart/volcano/templates/batch_v1alpha1_job.yaml
Labels: approved, lgtm, size/S

#11 Add v1alpha2 version CRD for podGroup and queue
  chart/volcano/templates/scheduling_v1alpha2_podgroup.yaml
  chart/volcano/templates/scheduling_v1alpha2_queue.yaml
Labels: approved, lgtm, size/M

#12 Update kube-batch to scheduler
  chart/volcano/README.md
  chart/volcano/values.yaml
  hack/run-e2e-kind.sh
Labels: approved, lgtm, size/XS

#13 Provide RBAC permission for v1alpha2
  chart/volcano/templates/scheduler.yaml
Labels: approved, lgtm, size/XS

#15 Update volcano-0.1.tgz to use v0.1 tag
  index.yaml
  package/volcano-0.1.tgz
Labels: approved, lgtm, size/XS
